import { Toaster } from "react-hot-toast";
import Header from "../components/Header";
import "./globals.css";
import AuthProvider from "./providers/authProvider";


export const metadata = {
  title: "Create Next App Jee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>


          <Header />

          {children}
        </AuthProvider>
        <Toaster toastOptions={{ duration: 700 }} />
      </body>
    </html>
  );
}
